<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-Q4TLVFB" failures="1" tests="7" name="Test" time="322.569" errors="0" timestamp="2021-10-26T18:42:13 IST">
  <testcase classname="sep29_Testcases.LoginTestcases" name="Logintest001" time="28.072"/>
  <testcase classname="sep29_Testcases.LoginTestcases" name="Logintest002" time="27.774"/>
  <testcase classname="sep29_Testcases.ContactUs" name="ContactUsTest001" time="16.517"/>
  <testcase classname="sep29_Testcases.ContactUs" name="ContactUsTest002" time="15.517"/>
  <testcase classname="sep29_Testcases.ContactUs" name="ContactUsTest003" time="11.541">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at sep29_Testcases.ContactUs.ContactUsTest003(ContactUs.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- ContactUsTest003 -->
  <testcase classname="sep29_Testcases.ContactUs" name="ContactUsTest004" time="14.022"/>
  <testcase classname="sep29_Testcases.ContactUs" name="ContactUsTest005" time="15.259"/>
  <testcase classname="Base.TestBase" name="@AfterTest testafter" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest testafter -->
  <testcase classname="Base.TestBase" name="@BeforeTest testbefore" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest testbefore -->
</testsuite> <!-- Test -->
